apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: nextcloud-collabora
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: nextcloud-collabora
  httpUpgrade:
    - type: websocket
  timeout:
    http:
      request: 0s
