# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:bbBoPiM=,iv:Xe6f1T8EzU6Rv/Xio+ZxWRFUqcNPtmx57ir7sVK58EI=,tag:Qv2Ttttcy1l9gSE+fgyl/w==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:CLFjNyPL3/KLLUuP4eyaa3NFYFTYGyqvChLasIkKVxbbEw6ECnXK9VsK9R1xGHjHV5uRtCLBM0x8,iv:1ibiFfvNUWsDDfHTqTrxaVL3SVhM5NyUORoQurUz6qA=,tag:47UncLy71gSxXisXUcVJ4g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:T5+XS6I=,iv:asNhP5KvKfwacqkC26XZNJcuz85L12L/MNWxVbBvoD0=,tag:x4IgixP18+/AuGswB3jTpg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:sgubqbZf28Qokvz1SOHCIEKZpuqF+H8oWmn8S3Aa8fc=,iv:3MI1kRdJ2zCbg0Qhw9r8HXM2OmDUMgNOXn6rBG6wTHE=,tag:qFsR1hWaRn52HtkUrZgkYw==,type:str]
    OIDC_DISCOVERURL: ENC[AES256_GCM,data:yjNkvcl0MMaIZbu9gYbtsDawbHSibfsStzmw/Ybukb8y6Q9NwelX8VmMGmorjjOFAMdAGlK/jZtj0wdxOkoTZE8kR8gsiR88n+Mj,iv:050+HjcZf98tcI8C21wypxERfbu2qTmm6K0YKGPiq84=,tag:hj3b0wNIkWvDMQHbtA/Cfg==,type:str]
    HOMEPAGE_VAR_NEXTCLOUD_KEY: ENC[AES256_GCM,data:BeHSGbgJma5a+lpuF45+gR25XseVFnjQx2g9sR8rHMsZiQdSw2aKMRwTlbh0Y2Yo0i5A4a0E95VA4IZ/xezq6M9MQFBsNnkLhW4WHw8=,iv:afdQ/VhabqWLAiVK9LybuHHg3QX50zLLseW5Lcr2YFs=,tag:dOxuvhcBVC+vqWxel9ep8A==,type:str]
    COLLABORA_USERNAME: ENC[AES256_GCM,data:92oBwGg=,iv:anjYEONaE5d5N+jc9HpYCEpyk7ts/7gwl4scZogqUYY=,tag:gJ+4thEd8+i8k1SonNuQpg==,type:str]
    COLLABORA_PASSWORD: ENC[AES256_GCM,data:X0eUOvtXiqShA0FQ9X0I3fQVXHhhn2QL26FRqteInvDwW0F8JA==,iv:cZfphtVilWEtEKV0Tzb3ZR1nzRVvlDbCEXKqizgds80=,tag:VkyFUVaH49pkAO4x61dbGw==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T14:20:39Z"
    mac: ENC[AES256_GCM,data:jPWVHFdloqw6SKKyrCmEFbtx2r3eHd6hc+Ao3Xy1u0mt7sh6MnDL0hiSm3jn0/+p2/ERVQytfAM4Y3gNjOXY9wjkZd9Kp+0EfMrM1nltkLH7P0gbggmJRfCjRZ8BbtBSIIWyAzuBAAcJ3ge53la2/1LgUyYlJpLKUy/Khh+FrXg=,iv:icV1TPNxqUgXUFMuH075J3MBv28DTRmzpxeUUP43h14=,tag:ckYaEUNV1iK2Nh9gYluZig==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
