apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:QWKt776dRuF7SQOsg+7hloQLjVtBP5+SBtwv2dnvDjQ=,iv:A32w3NleA/Du74EfWG/HvXO71rVLgFsvVNG+sRzkuCU=,tag:YjPs9JLGdpjDLGCyVTN5tA==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
            N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
            Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
            K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
            7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:07:32Z"
    mac: ENC[AES256_GCM,data:7CLDyoqgQGGiMjdx/wiY+0EgyUzZJ165VjwkC5k4l/YoZrtOFseGGWVW8pYuAQ6pgVy5swmWThApj3WAuENoezGL4aWb44MieDfgCq0YJDdBf4SDrENzlm35llg4yoxeM7fwk4t2n85sORuMXPIWdJ24xrZCiS9m5xUoMYYYZdE=,iv:Y4PPcALaQ4jBtYQd26MGL7D5TFVb3V/xuNFjH9oVIKg=,tag:ReNquC5iXu4eCnk/C7xXug==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
