- Bookmarks:
    - kubesearch:
        - icon: kubernetes
          href: https://kubesearch.dev
          description: Kubesearch HelmReleases
    - onedr0p home-ops:
        - icon: github-light
          href: https://github.com/onedr0p/home-ops
          description: onedr0p HomeOps Repository
    - bjw-s Chart Values:
        - icon: github-light
          href: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common#values
          description: app-template Helm Chart Values
    - NixOS Search:
        - icon: nixos
          href: https://search.nixos.org
          description: Search NixOS Packages and Options