apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:nPITe97pFOVEeF40C5L3Id+63BAVDmn/GJhxCSOGQF5z6dsoI63WnkHTjP+ujLsZcAa9tv1S/geW10dsrclpB4XY/YdcehJNwRvbs/BHQ+DeUGhLnxWtfVN4ju308REH2iZkJmop4MEa8v/Lq3HWeJGOnygb1qJhScR+VMuoeJPE3BnRv3q83+MoP4dWU6LTOgri72m3kXNtE2yMjNiZ6mhyMr/Ii8yUKmysipk2//qrGSjiaCE7frSmFm1QEOYeD9+CKNfN6RIAUilgWeiyDsUiQ9IV1WtS0gyGPLl0/jc8aXZTtTSYy2bpsM4/xtlhNJBeTk4zXhJHQWuCc2L9uNOlXW904jlDMtHxTemixvjMRZ/1hbIX8LdK1njp8k2Om65L+LkbQqCfaiQ/I/Wx77D8LWFB1UVvJkfOF0xmi4lu60R8DBMSezkZmt6l4dB2/yk9+NqRP9M7djg/hAuwJjBj0GJzWl8r,iv:hek7C7PbG7qq6EBe1Yk4TyZQ0YSszmSie7t03UVmhpo=,tag:BPZCETeIeXoaiVLsv9vqrA==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T09:55:36Z"
    mac: ENC[AES256_GCM,data:+o9EG3EMuk9n1slC+Ec/sBQZdSvM6GOTIJ+Rq3ZOQsO7Y+Cga2ocUhcIvT7EY/Km1Lc1+jRILR+lgBNxqDvUKF0344jp90buvoBDp1iKmlpATnrAFIc3V3dF2/qHVY186V1oNwV/yN0rhVRF610fq/Zjm/P74IO0KsE5o1yF8LY=,iv:oCwnAagfXLmzVyk9KBG7b+oG0rPsPQUKnsp4HwZkpkU=,tag:8FFsNx5EHXRm4MOkzRfrzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
