apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:bc4uYgk1sYVsbii80GEf9/7HayQHpv3Fsp7auZ/ZLetv8XiXJGGNnwwr/pNlP/tklDn0CmUOIbuabBpl7+Mw88U7qaG1LkIVNB3Gh10QuBe94uSHbXvmNcP6o1niMXMfsyQbZcpgYllvdMu7r8m2+TzJ5fHhM3Jk1C8clj+GB4jhWnmJeKBXwLDQong5GfBIKdzYpJHXa5E47T8fkZ1+tDoxTmILgdDvDIYp1y7K3CQkYA6UnDfnP55Um0lnkSXyRAV2spt/qBWPuKaVY8oZX/AuzfsRAmvGeHWfFy7bBXGB7PKG4YVvwjJ5HkAR/B3sUUYm/33yqt03fr1HE34dvwi0wC8AHLzWJjAP6GZXVNu9npxyPJMjTB7cqa+Si9PcwsB35kOGLVEYsX0eiB0A2FLwsspok5pGzKyaM6/F96VXBhmMHvpUnxMVCvCiEfpG1ZCKdf4pBrcONB0MgRx+SSvPSiyeLWfeb2KxsaEoILI=,iv:wig6+s6eadM55fv/ARZFFG+5uiOtt8Zf629dFta4vgA=,tag:vB9sGULsxvQK6a0QRVzAkA==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T22:14:17Z"
    mac: ENC[AES256_GCM,data:mdA6xgk3gRxlX2p3TI3FoOUcTAPtrXcWIe6b3LKDAyFAQrGLi1tdcTHWtWWx7543rnsN+xidyk1eShd5ezsCLj1TNzSgyCRnJa3ZTNwldgRw4qsjM9GkM8FUPfHwU4RTbTdcNvYfADPrHRFHvKM+1q+1JTbLs2YEu8Gqp5mLuCc=,iv:i+t9QlKC2q+hV9kkHlf5tyj0zekML4/i69UKsVCaFhc=,tag:FzvM981oVv2MRopqEQgB3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
