apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values-secret
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:jed6dRlFZe4g4J4sKAfL47AWgKX+6Sz1nH6kel8H5JzdUpiyqaeqkbZgCTaGESPD+utP8Kqf6z6o0Ps0CzHBki0cMYHn7MUB7tN+bKxpAvulm42Z+LVxWnG+yMuK1fFeIUGKRQB8vTeRCjCgbjpEoIxAKXl8L8AGKEduQD2jnpbcl7U=,iv:jDPmb7W8UrI7bir9AW2NAx0kUf9ONitJvaRW2ee+/Jw=,tag:FkQ7lP+ZAc8Ff5PZ+J2FmA==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:17:14Z"
    mac: ENC[AES256_GCM,data:FQhzJ/ytD/KKq7Z9anEwBxOs6p1ddqT5cKyx/77QnqcuckOmeZdN4OYBP9TYf+9OLxU1PPtYGCIfCNv8Zjbo3MMW4alxMrmAXaJ0gvx7j9QOC3CTtLTdq/SwT1uuZJ6A3pZcQ1MBxZMZOG7Fbzl8apti6EL3FNfF6bTiAuBEk/g=,iv:kFmjXwQGvx2es0zC2qthT9DRD5kiBxVdlxp0rePLY7U=,tag:6zzjlwy0Z2ag6/rxJk7Bcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
