apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ej3BVSadrWdzN3SCra/DaXDx0miiBCzoS56HLiveg8X6elU6JnwnBALtCer7SeHM/NgkQFOM04SGa1bPrpFJIKv6G0NK2u067NENpGZZqEqcFEiiU+CVtJwG8hvs3tkUoBFIxGdCsQldXLtQNEbDk7svWCI1XlHyxX/DbETjvPTI+djm7S4uq9IcJ5714bzqAQAapC6us5XccbS4wMz7SXqc716OHuI7rQ1edo2ekdM5kLBu1A10eegWGg9ibppmUbB5f7s6O8mT2Ko1TYU3Hh9g0ahq/WVXP4UDREx2BQtxVHPNYrirYM0kpCzc9psGSO1SFqQgMP15ou+cM/VyUZfI5/97G74r9a5xusCbdp6OAR5QwGJAIvj8uQFjuad1WMZijPxO38p4iKLq+07yvXcO/g44XQ==,iv:kyytkIDDDG8dj1VfJ45JodLbrjSXV0Ga0aLYNtvzalI=,tag:4daxMAIu8bjrxh9jIWMrhA==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T08:56:16Z"
    mac: ENC[AES256_GCM,data:eF5XRK2sp14cub18DbAeOSOa8vwLFt4Ds3itq+ofDkvBpy8yuM93UCO1tEIrXoRQsdNweXVbNM6gkwRbFKIT1pVbZFvbWi0gNb/cNYFCeASYR7lq1+u3jvden+o9VAMRULDYetzNvEtUY5gqq89Ape455t8s9n+t3L5jrae5Li8=,iv:yd/Su3iL8L5mlEOgxdiDfpWtEmoNUYU9Gl4UKeowPQE=,tag:M7bwlj7cEB2VrHgOBu4kEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
