apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values
type: Opaque
stringData:
    oauth2: ENC[AES256_GCM,data:0uUTxOsxmdugw5SFBIUFN6bVOwt/399xHhauyb7qtsiQI+rikde5apRC7wh9yWSeLUga+YMjfSK51GWUXMFkAwJ7,iv:xB3rh9npW29lv1ILQ8u465G22pPSQL51ZgDbX/4Wnp0=,tag:q726hEy3ixeq4HBmnaei2A==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:59:31Z"
    mac: ENC[AES256_GCM,data:NXHS5v6FbpqzTnw09t0xoDdv4RTTSrmRHRFIljz/2JqOfCYmaeX1ZfVcxnzhD38fbdMsNd/wj2BG4geYbGk36zyc5xQ3R6xXQ7a1nTsH1lgfBcFCHueaQtp7tSIdKSozn192cTmeDuV4dacZhLHv6rXzxSvnoDo2NLG1ihtsajE=,iv:sIQCys4Hb5cUyXlqhYCfCFV5xq6Yqlbewij0I+/0YoY=,tag:ub7xipGHQa9/W+5xlX4xDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
