apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-helm-values-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:xPj3xlbPuiIpdXA/jrA84GUDFrA9vxRGak7BgdRlf2G4+ga1oZaqXjt1mTHcLGTGeGfJ9g3kZ5xdX5HOznolVWb9YHm7Ws+mKKRFGjh73je583w8UNOsaRmEzxW3kgpAWMGM1xvJn0hgMiVVCnHo38ysqvuC3PtBvFtT9XM0a8tlXa5iSg9RW/BmQR7W2w6EvTFqGUJpjrakCaGKlyBdCMNCZrFz0zbYcQ9HocpPMuR2yXda4KiARVXYzw0JeLAi141BOdbmwoBU2Xi/jB79wTO6KEQxcwM+p6hrlJAYO46inbRIe3dHCI46W8ulfoQ5ewc2rtDErvIdcZfPychs712HA2Pzxb5FC0b1tM0G4BJOjiD19sLkB3+aUb4I+7w5nPDJL2eBFVIvKLal+N82oQRuquiAyIudoUh0g0hi8EWw82mXVYD4BVVYllLb7/9tKG+ULu1GfAhst8Vi4oCQ6nmM7tz5gKN1YNRC0NiO,iv:CCrFZumECsdi1LOO7JL1+VBsHM0LdiUubYFItNPqBMI=,tag:WGfRaEm0hv9rr87ybU05bw==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTVOdUdQeUgrSlpoa2tS
            blA0d3Q3YmNZTkowWk9NZjI3NkFJNVJSM0J3CkpkZFRHYkt5bTZrMXlLcENKb1F3
            L2sxMk44LzZMUWEvMDhTWXI3RlNpa00KLS0tIGhjNEs5UHgxU1J5RWQranFrK2ZD
            VGl5aFhVcjUyUG4xSy9tYlQ5M0RaODAKjUnt2FMDgYQ/6GsiKtSAl5paSOVMPHMs
            E9QeUlhvpq+DYp/Y8kgKt1PbDCjRgSFeU3oOhFtx4m6xmWhsW9xZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T16:08:41Z"
    mac: ENC[AES256_GCM,data:3NpnTJQQJgQfRLU5Mc8nxwSJnWtwTobOFxN0I3+lmB90eCvc9X+mzCrl39fvSxBmes/FmUpgunTvDxsPTkrOLwgIGvJyOKhTCaxNqqncOZaeob51dFP7+oyt26rTPUYBx4Bd9778FA0NKXoDW6jbvILVuyKMVSuy485YrWtiGTY=,iv:bwVGvM04e6cruCsLhnXgebOBUvJ4NP/cyCBD6O6Zyjc=,tag:uaSspU3HkTDzh9jukvdiAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
