apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:x7QV+EbY5igOGRT0jc5bjoc6pHNqznaNwP92e31BID47Hmwk0J+IKehZ6w==,iv:kKzaWrWtK5DjcIyFQYoPG3m1sJN+HgQBM5Y8uEADKVY=,tag:1k+DHpKDj/ItjQMam2BSug==,type:str]
    HOMEPAGE_VAR_OPNSENSE_KEY: ENC[AES256_GCM,data:wKHm5aDrJrV0ik+QFW+EyUDbOVpx08oBzNq2wHCo4cJB4WMt7tvTRs+wOQTSQG1u/I3+a7p+tAJQSBNFZQfReQjatouxqR4xTWrHLph19I0=,iv:wkFvFk1o8hb0KhywE9E0y3MpZHUAbeiBdU8aBSbnjcc=,tag:S2HGEjC23BQN7iyVhrer5w==,type:str]
    HOMEPAGE_VAR_OPNSENSE_SECRET: ENC[AES256_GCM,data:mF+r5L4vuvtonAdE01ygR7a1iXcklAiCd9v/etYeD1yktsnScc0kCFEfBwv/YtPqjSVt9bRSzWT/wgYKQ7NN+GThgpj66N3nXfK/LyNU5pg=,iv:h0qaIgFEBbdANAFURWN0ywWp/nBMyFxSoJNgm3uzfKE=,tag:e3K8flq8AG0x0pVvQXo4Vg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:9lYyKxkYyyPNtVhXg/ZzXDsOjat4AY6BGoTNppZo3ZU=,iv:s3fF7qCe627qK8C35HGtE99LObgMOezxK5PeUrWkGYo=,tag:JSS48ptJTmD/ae8iCYNzCA==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:5OpgmsbZFt8WEVWNNDpbELRJZMcwkO5iSJvI2SDwxWg=,iv:EWG4AJzjde3hkQNb1wHEh9oDMpXOcNoHmGZiwj7LiKk=,tag:re1SCLGvSlHAnbVTTaeKTQ==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVGptbElFc3VqelRKQWoy
            K1pJOE1tMk94RDFyVmFqMzB3ZWZMdnBWbXljCkVqSm42MXE3NVk4cHZXVHA5VlE4
            VCtvTHNQWHVTOEdwd1JjWSt4SC9iemsKLS0tIDRYdFJyQndKUzR0OCtrSW9VRVph
            RjgvM3NqTy9TZzdqZytSSzZ1K1Y2REUK/7XX/m4y6f/HRykdiV+2fiwYtxX1wMk/
            du6us0aUi3e3MckrqXzSOPAbHBIwQUtoNxa1U1cGAlcVObePJW/j2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T23:17:35Z"
    mac: ENC[AES256_GCM,data:7wskj+QWFBkCTE1XYSZPq3e5RI88tUvS3SoDYYf4Wn8zu/v9BPaXqAnEb+RMgfT19qPtNjma3LYMVt3zgC/p5TBw5EBDUBaJDbac6xNP1fEDMNvCQgVeq8g3vk8qsCakwGb7epzviJPTEwKJ+rMxLX8uvz7RgNsMerJQikCyIVw=,iv:8GHgCHy9MGxsc+r4xCrsZ32yzue6katvF9I4pOfaptQ=,tag:Oq6yjbEIgtJI3l0HFU46dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
